### PR TITLE
checkout use case and interface adapter

### PR DESCRIPTION
**Pull request by yuching530**
checkout use case and interface adapter.

### CODE REVIEW

**Comment by yuching530** [comment]
tell me if i need to change attributes

**Comment by AeyshaMun** [comment]
This looks good! Just wanted to clarify something really quickly: is guestID the ID provided by the mongodb database, or is it their name, which they use with their room number to sign in and stuff?

**Comment by yuching530** [comment]
Sorry, i just pulled out to see the updated ver. of entities that you and olivia created right after i pushed mine. I think it will make much more sense to use guest name instead of guest id right?

**Comment by AeyshaMun** [comment]
Yes I think so

**Comment by yuching530** [comment]
Hi, I just realize I did not handle clients and event hall. I got a question, so for checkout do I have to put extra client and event hall attributes? Or the user’s name and their room number is sufficient enough. Cuz I remember that event halls are just other “rooms.” For my input data, can i change from (private final String guestName; private final int roomNumber); to (private final String name; private final int roomNumber;private final boolean isEventHall;)

**Comment by nogaaltman** [comment]
This looks good! I think it would be good to have a back button that redirects users to the logged in view, in case they ended up in "checkout" by mistake. You would need to add a "swtichToLoggedInView" method which switches the state to that of the logged in view. This method would go in the controller, interactor, and presenter. Great job following the clean architecture flow in your packaging and methods!

**Pull request merged**
