### PR TITLE
Added Logged In, Login, Place order, Main Page use cases

### PR DESCRIPTION
**Pull request by nogaaltman**

### CODE REVIEW

**Comment by AeyshaMun** [comment]
This looks great! A couple of notes though: it looks like you have a couple of methods that you aren't using (e.g the getItem methods in the PlaceOrderState), so feel free to get rid of those if you're confident they might not be accessed in the future, or you can keep them in case of future extension. Also, as a suggestion, you could keep track of the selected page (book a room, book a private event, my booking) in your main page state.

**Comment by AeyshaMun** [comment]
Oh, and for you import statements, you don't necessarily need the full path (main.java....), you should be able to get rid of the main.java part.

**Comment by ayushathapa16** [comment]
Ayesha, I am not sure if removing "main.java" from the beginning of import statements works. When I tried doing so in my classes, it showed up as an error. If the code works fine on your end without stating the full path, then I am unsure why it does not work on my end.

**Comment by ayushathapa16** [comment]
Hi Noga, I wanted to commend you on your design choice of creating a ReceiptViewModel, ReceiptView, and ReceiptState. It’s an incredibly thoughtful and effective decision! For my use case, I had assumed that when users book a room, a simple pop-up would serve as the confirmation. However, after reviewing your implementation of the Order Food use case, I now realize that designing a separate view for confirmation is a much more versatile and scalable approach. This design not only aligns well with the overall clean architecture but also makes it significantly easier for me to implement the prepareSuccessView method for the booking use case. Great work on this design—your approach has clarified the path forward for my part of the project!

**Comment by AeyshaMun** [comment]
> Ayesha, I am not sure if removing "main.java" from the beginning of import statements works. When I tried doing so in my classes, it showed up as an error. If the code works fine on your end without stating the full path, then I am unsure why it does not work on my end.

Yeah I'm not sure. It works for a couple of my files but I just noticed that it doesn't work for all of them. I'm not sure why that's the case. It seems like Noga doesn't need the full file path, nor did the example in Lab 5.

**Pull request merged**
