### PR TITLE
Completed Private Event Booking User Story

### PR DESCRIPTION
**Pull request by AeyshaMun**
I'm 99% sure I'm done with my user story, feel free to look through stuff and lmk if I could fix the structure based on clean architecture, SOLID, or if I need to fix things to be able to save to the DAO. Oh, and I still have to figure out the interfaces for some of the entities, so I'll fix that as needed

### CODE REVIEW

**Comment by AeyshaMun** [comment]
Okay so I figured out the shared interfaces for the private event booking and room booking user stories! I didn't mean for it to be one giant pull request alongside my previous commits, but I guess GitHub added them all together since the first pull request I made hadn't been accepted.

**Comment by ayushathapa16** [comment]
Hey Ayesha, I looked over your pull request, and I hope that the current implementation of the Room Factory works better than what we had previously done. I'll let you know if we need to make any further modifications to the Room Interface.

**Comment by nogaaltman** [comment]
This looks great! The code is well organized and easy to follow. I only have a few ideas about improving some things. First, I don't see an interface or factory for your event forecast entity, so I think those would be good to add. Second, small note but I think there are a few unused variables that you can take out ( e.g. In EventForecastInteractor you don't need the UnsuitableForOutdoor variable). Also, add imports to WeatherService! Overall this looks really good. You're sticking well to clean architecture and your code has a very clear flow.

**Comment by nogaaltman** [comment]
Also add imports in WeatherService! Things are looking good though

**Comment by ayushathapa16** [comment]
Hi Ayesha, thank you for creating the Room and RoomFactory interfaces—they are a solid foundation for our project! I wanted to bring up a point regarding consistency and functionality in our code. In Lab 5 (our reference project), the User and CommonUser classes share getter methods through their interface. However, I noticed that in our current implementation, Room and Suite do not share similar getter methods. This lack of shared methods is making it challenging to implement the execute method of the BookRoomDataAccessInterface effectively. To address this while maintaining the Room interface, I have introduced a getRoomType() method. This addition ensures compatibility between Room and Suite, allowing us to preserve the abstraction of the Room interface while supporting the functionality required by both entities.

**Pull request merged**
